keys:
  - &vasily_laptop age1u2sdxwxg0j8748jx26rmwm2len36xe2tl58sxtgtf3k3mspuydgqn8usdq
  - &server_ranger age1erzdjw7fa5g3yxmafkqy3w2wwc62q3jj4v6wdhjl9axzg0kssswqwdr78u
creation_rules:
  - path_regex: ranger-nixos/secrets/.*$
    key_groups:
    - age:
      - *vasily_laptop
      - *server_ranger